### ISSUE TITLE
docs: stateful-agents.md shows wrong send_event/post_event signatures

### ISSUE THREAD

**Issue by dhyansraj** [dhyansraj/mcp-mesh#1055]
## Summary

The `docs/concepts/stateful-agents.md` event-injection paragraph (introduced in #1053) shows the wrong API signatures for `proxy.send_event` and `mesh.jobs.post_event`.

## Bug

Current text (post-#1053):
> Producer-side `proxy.send_event(payload)` (or `mesh.jobs.post_event(job_id, ...)` from a caller that doesn't already have a proxy)

`send_event` is documented as taking only `payload`, but the actual SDK signature is `send_event(event_type, payload)`. The `post_event` example hides the required `event_type` parameter under `...`.

Authoritative signatures:

- `src/runtime/core/src/jobs_py.rs:487` — `send_event(event_type: str, payload: Any) -> dict`
- `src/runtime/python/mesh/jobs.py:226-229` — `post_event(job_id: str, event_type: str, payload: Optional[dict] = None) -> dict`

A reader copying the example from stateful-agents.md as-is would get a `TypeError: send_event() missing 1 required positional argument`.

## Fix

Rewrite the paragraph to show the correct positional signatures:

- `proxy.send_event(payload)` → `proxy.send_event(event_type, payload)`
- `mesh.jobs.post_event(job_id, ...)` → `mesh.jobs.post_event(job_id, event_type, payload)`

The canonical conceptual surface at `docs/concepts/jobs.md` already shows the correct signatures — this is a one-paragraph drift in the stateful-agents.md cross-link.

## Out of scope

This issue covers ONLY the inline-prose signatures in `docs/concepts/stateful-agents.md`. The longer code examples in `docs/concepts/jobs.md` and the meshctl man pages already use the correct signatures.
